{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: tls-{{ template "nats.name" . }}-server
  labels:
    app: {{ template "nats.name" . }}
    chart: {{ template "nats.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ template "nats.name" . }}
type: Opaque
data:
{{ (.Files.Glob "server/*").AsSecrets | indent 2}}
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-{{ template "nats.name" . }}-client
  labels:
    app: {{ template "nats.name" . }}
    chart: {{ template "nats.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ template "nats.name" . }}
type: Opaque
data:
  {{ (.Files.Glob "client/*").AsSecrets | indent 2}}
{{- end }}
